"""add_pagination_indexes

Revision ID: 95b8c7e87dbb
Revises: 1c6a5cfc35f2
Create Date: 2026-02-20 04:12:09.022847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95b8c7e87dbb'
down_revision = '1c6a5cfc35f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_book_created_at'), 'book', ['created_at'], unique=False)
    op.create_index(op.f('ix_borrow_record_borrowed_at'), 'borrow_record', ['borrowed_at'], unique=False)
    op.create_index(op.f('ix_borrow_record_due_date'), 'borrow_record', ['due_date'], unique=False)
    op.create_index(op.f('ix_member_created_at'), 'member', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_member_created_at'), table_name='member')
    op.drop_index(op.f('ix_borrow_record_due_date'), table_name='borrow_record')
    op.drop_index(op.f('ix_borrow_record_borrowed_at'), table_name='borrow_record')
    op.drop_index(op.f('ix_book_created_at'), table_name='book')
    # ### end Alembic commands ###
