"""add_analytics_indexes

Revision ID: ad79da468ca0
Revises: 95b8c7e87dbb
Create Date: 2026-02-20 10:23:44.224998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad79da468ca0'
down_revision = '95b8c7e87dbb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
