"""Add version_id to book

Revision ID: b792a29b3dbf
Revises: df24534f12d6
Create Date: 2026-02-20 00:16:24.177880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b792a29b3dbf'
down_revision = 'df24534f12d6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('version_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'version_id')
    # ### end Alembic commands ###
