"""Add GIN trigram indexes for search

Revision ID: 65b4dc23dbc6
Revises: 667037d7a76d
Create Date: 2026-02-21 13:10:01.102596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65b4dc23dbc6'
down_revision = '667037d7a76d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS pg_trgm')
    
    op.execute('CREATE INDEX IF NOT EXISTS ix_book_title_trgm ON book USING gin (title gin_trgm_ops)')
    op.execute('CREATE INDEX IF NOT EXISTS ix_book_author_trgm ON book USING gin (author gin_trgm_ops)')
    op.execute('CREATE INDEX IF NOT EXISTS ix_book_isbn_trgm ON book USING gin (isbn gin_trgm_ops)')
    
    op.execute('CREATE INDEX IF NOT EXISTS ix_member_name_trgm ON member USING gin (name gin_trgm_ops)')
    op.execute('CREATE INDEX IF NOT EXISTS ix_member_email_trgm ON member USING gin (email gin_trgm_ops)')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP INDEX IF EXISTS ix_member_email_trgm')
    op.execute('DROP INDEX IF EXISTS ix_member_name_trgm')
    op.execute('DROP INDEX IF EXISTS ix_book_isbn_trgm')
    op.execute('DROP INDEX IF EXISTS ix_book_author_trgm')
    op.execute('DROP INDEX IF EXISTS ix_book_title_trgm')
    op.execute('DROP EXTENSION IF EXISTS pg_trgm')
    # ### end Alembic commands ###
