"""Add B-Tree indexes to BorrowRecord foreign keys and status

Revision ID: 667037d7a76d
Revises: 8d8bbb389bc4
Create Date: 2026-02-21 11:44:59.093138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '667037d7a76d'
down_revision = '8d8bbb389bc4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_borrow_record_status'), 'borrow_record', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_borrow_record_status'), table_name='borrow_record')
    # ### end Alembic commands ###
