"""add_advanced_features_audit_and_soft_delete

Revision ID: e51d53eb64ce
Revises: 65b4dc23dbc6
Create Date: 2026-02-25 00:03:34.210065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e51d53eb64ce'
down_revision = '65b4dc23dbc6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditlog',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('old_state', sa.JSON(), nullable=True),
    sa.Column('new_state', sa.JSON(), nullable=True),
    sa.Column('actor_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_log_entity_composite', 'auditlog', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_auditlog_action'), 'auditlog', ['action'], unique=False)
    op.create_index(op.f('ix_auditlog_created_at'), 'auditlog', ['created_at'], unique=False)
    op.create_index(op.f('ix_auditlog_entity_id'), 'auditlog', ['entity_id'], unique=False)
    op.create_index(op.f('ix_auditlog_entity_type'), 'auditlog', ['entity_type'], unique=False)
    op.create_index(op.f('ix_auditlog_id'), 'auditlog', ['id'], unique=False)
    op.add_column('book', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_book_deleted_at'), 'book', ['deleted_at'], unique=False)
    op.add_column('member', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_member_deleted_at'), 'member', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_member_deleted_at'), table_name='member')
    op.drop_column('member', 'deleted_at')
    op.drop_index(op.f('ix_book_deleted_at'), table_name='book')
    op.drop_column('book', 'deleted_at')
    op.drop_index(op.f('ix_auditlog_id'), table_name='auditlog')
    op.drop_index(op.f('ix_auditlog_entity_type'), table_name='auditlog')
    op.drop_index(op.f('ix_auditlog_entity_id'), table_name='auditlog')
    op.drop_index(op.f('ix_auditlog_created_at'), table_name='auditlog')
    op.drop_index(op.f('ix_auditlog_action'), table_name='auditlog')
    op.drop_index('ix_audit_log_entity_composite', table_name='auditlog')
    op.drop_table('auditlog')
    # ### end Alembic commands ###
